services:
  - type: web
    name: your-app-name
    runtime: php
    env: php
    buildCommand: "cd trivia-backend && ./build.sh"
    startCommand: "cd trivia-backend && php -S 0.0.0.0:$PORT -t public"
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        generateValue: true
      - key: APP_DEBUG
        value: false
      - key: DB_CONNECTION
        value: mysql  