services:
  - type: web
    name: your-app-name
    runtime: php
    buildCommand: "./build.sh"
    startCommand: "php -S 0.0.0.0:8000 -t public"
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        generateValue: true
      - key: APP_DEBUG
        value: false
      - key: DB_CONNECTION
        value: mysql  