services:
  - type: web
    name: laravel-docker
    runtime: docker
    dockerfilePath: trivia-backend/Dockerfile
    dockerBuildArgs:
      - key: APP_ENV
        value: production
    envVars:
      - key: APP_KEY
        generateValue: true